
all:
	cd ddslib && $(MAKE)
	cd etclib && $(MAKE)
	cd filematch && $(MAKE)
	cd l_net && $(MAKE)
	cd mathlib && $(MAKE)
	cd picomodel && $(MAKE)

clean:
	cd ddslib && $(MAKE) clean
	cd etclib && $(MAKE) clean
	cd filematch && $(MAKE) clean
	cd l_net && $(MAKE) clean
	cd mathlib && $(MAKE) clean
	cd picomodel && $(MAKE) clean
